### ISSUE TITLE
Add Yeelight YLXD50YL (yeelink.light.ceiling20) support

### ISSUE THREAD

**Issue by chris-nite** [syssi/esphome-yeelight-ceiling-light#19]
Hello @syssi ,
thanks again for your great support. As my meteorite lamp is running smoothly since i've upgraded to esphome, i now would like to address my struggling Ceiling Lamp Yeelight YLXD50YL (yeelight ceiling lamp 20), as it is almost always unavailable in HA, as well as there are problems using my CW-LEDs.
This Lamp got a combined Lumen output of 7200lm, as well as a color-LED-Stripe facing to the ceiling.
So far it seems no one have documented anything about this lamp yet, so i teared it apart to see, what i'm working with:

<img src="https://user-images.githubusercontent.com/65537552/130954340-78942795-3055-433f-80be-072ee8d8eeee.jpg" width="60%">
<img src="https://user-images.githubusercontent.com/65537552/130954345-7a0d6354-ac59-49d9-8dfb-0e92209e0300.jpg" width="60%">
<img src="https://user-images.githubusercontent.com/65537552/130954349-e5c6dff8-03bb-4005-983e-0b3d061e6d47.jpg" width="60%">
<img src="https://user-images.githubusercontent.com/65537552/130954351-5441e5c8-b856-4580-8ec7-921650d51439.jpg" width="60%">
<img src="https://user-images.githubusercontent.com/65537552/130954354-5cccbd2b-0f50-4bab-8ba6-226a20f15698.jpg" width="60%">
<img src="https://user-images.githubusercontent.com/65537552/130954357-32e459f6-64ac-4ef1-98a2-e8b1f352da31.jpg" width="60%">
<img src="https://user-images.githubusercontent.com/65537552/130954360-5184ded6-93ce-4879-a01e-ae9ebde94073.jpg" width="60%">

It seems to use a ESP-WROOM-32D Controller on a small WIFI CTRL-Board (VZ6REV 0.1), which fortunately can be removed from the mainboard. The provided PINs allow to directly mount a cable to 3.3V, GND, ADC1, STA. 
There are little testpoints from TP1 to TP5.
So far i was unable to find any TX/RX-PINs, so i guess they're hidden in two of these TP, as well as GND0.

I assume as soon as we now, which of those points are important for flashing, it's only a matter of time to get esphome on it.

Do you got hints or any documentation about this Controller @syssi to get started with an USB UART-TTL-Adapter? How is it possible to find out those missing PINs necessary for a flash?

Thanks in advance and best regards.
Chris

**Comment by chris-nite** [comment]
In the end i've measured all the voltages and set up some values near those OEM-lmits. 
Unfortunately because of the color wheel of HA, it was especially hard to get pure green, blue and red-settings to get the measurements right for those channels. Interestingly mixed colors seemed to somehow increase the voltage especially on the blue channel, than the strongest and purest blue tones (maybe the brightness is getting increased when using mixed colors).
I've to add, that i've not changed minimum voltage limits in the configuration (even though the 0 value is a bit lower than the OEM minimum voltages), because the leds were actually capable of driving lower brightness-levels in esphome than in the stock images, which i prefer.
Unfortunately I couldn't test the cold white leds so far, as the power driving circuit seems to be defect for those (which seem to be a common problem for this light), so i'll have to live with a dimmable warm white light.

Alright, the values are not perfect, but pretty accurate and near those original values, so here you go with my esphome yaml for the light:
```
substitutions:
  name: yeelight_light_ceiling20

esphome:
  name: ${name}
  platform: ESP32
  board: esp32doit-devkit-v1
  platformio_options:
    platform: espressif32@3.0.0
    platform_packages: tasmota/framework-arduinoespressif32 @ 3.10006.210420

wifi:
  ssid: -------
  password: -------
  fast_connect: true

ota:
api:
logger:

output:
  - platform: ledc
    pin: GPIO19
    id: output_warm
    max_power: 0.490
    power_supply: power
  - platform: ledc
    pin: GPIO21
    id: output_cold
    max_power: 0.98
    power_supply: power

  - platform: ledc
    pin: GPIO23
    id: output_nightlight
    power_supply: power
    
  - platform: ledc
    pin: GPIO33
    id: output_red
    max_power: 0.229
    power_supply: power
  - platform: ledc
    pin: GPIO26
    id: output_green
    max_power: 0.454
    power_supply: power
  - platform: ledc
    pin: GPIO27
    id: output_blue
    max_power: 0.7
    power_supply: power

power_supply:
  - id: power
    pin: GPIO22
    enable_time: 0s
    keep_on_time: 0s

light:
  - platform: cwww
    name: "${name} ceiling light"
    id: ceiling_light
    cold_white: output_cold
    warm_white: output_warm
    cold_white_color_temperature: 6500 K
    warm_white_color_temperature: 2700 K
    constant_brightness: true
    gamma_correct: 0
  - platform: monochromatic
    name: "${name} night light"
    id: night_light
    output: output_nightlight
    gamma_correct: 0
    on_turn_on:
      - light.turn_off: ceiling_light
  - platform: rgb
    name: "${name} ambient light"
    red: output_red
    green: output_green
    blue: output_blue
    gamma_correct: 0
```
