### ISSUE TITLE
YLXD41YL bootloop in esphome 2022.12

### ISSUE THREAD

**Issue by bedson87** [syssi/esphome-yeelight-ceiling-light#63]
Hi, I have a problem with the lamp after updating to esphome version 2022.12 it goes into bootloop. Anyone else noticed problems? The config and serial logs are attached. Unfortunately, I had to disassemble the lamp and flash the 2022.11.5 version.
[serial_logs_reboot.txt](https://github.com/syssi/esphome-yeelight-ceiling-light/files/10251879/serial_logs_reboot.txt)

```
# merged configuration of:
# - https://github.com/syssi/esphome-yeelight-ceiling-light/blob/main/yeelight_light_ceiling15.yaml
# - https://github.com/jaddel/ESPHome-Configurations/blob/master/Devices/Ceiling%20Yeelight%20YLXD41YL/ceiling_yeelight_ylxd41xl.yaml

substitutions:
  name: kuchnia-yeelight-ceiling
#  external_components_source: github://syssi/esphome-yeelight-ceiling-light@main

esphome:
  name: ${name}

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_FREERTOS_UNICORE: y
    advanced:
      ignore_efuse_mac_crc: true

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: 192.168.10.21
  fast_connect: on
  manual_ip:
    static_ip: 192.168.10.21
    gateway: 192.168.10.1
    subnet: 255.255.255.0

ota:
  password: "XXXXXXX"
api:
logger:

sensor:
  - platform: adc
    pin: GPIO36
    name: "${name} adc1"
    attenuation: 11db
  - platform: adc
    pin: GPIO32
    name: "${name} adc2"
    attenuation: 11db
#dodatkowe sensory
  - platform: uptime
    name: "${name} Last Restart"
    update_interval: 300s
    device_class: "timestamp"
    unit_of_measurement: ""
    filters:
      - lambda: |-
          auto time = id(homeassistant_time).now();
          if (time.is_valid()) {
            return int(time.timestamp) - int(x);
          } else {
            return {};
          }
  - platform: wifi_signal
    name: "${name} WiFi Signal"
    update_interval: 300s
    device_class: "signal_strength"

output:
  - platform: ledc
    pin: GPIO19
    id: output_warm
    frequency: 4882Hz
  - platform: ledc
    pin: GPIO21
    id: output_cold
    frequency: 4882Hz
  - platform: ledc
    pin: GPIO23
    id: output_nightlight
    frequency: 19531Hz

light:
  - platform: monochromatic
    name: "${name}-nightlight"
    id: night_light
    output: output_nightlight
    gamma_correct: 0.7
    on_turn_on:
      - light.turn_off: ceiling_light
  - platform: cwww
    name: "${name}"
    id: ceiling_light
    cold_white: output_cold
    warm_white: output_warm
    cold_white_color_temperature: 6500 K
    warm_white_color_temperature: 2700 K
    constant_brightness: true
    gamma_correct: 0.4
    on_turn_on:
      - light.turn_off: night_light

time:
  - platform: homeassistant
    id: homeassistant_time
```
