### ISSUE TITLE
Yeelight Ceiling Light Bluetooth Remote

### ISSUE THREAD

**Issue by jaddel** [syssi/esphome-yeelight-ceiling-light#9]
Did you already made any attempts to get the Bluetooth remote working?

**Comment by syssi** [comment]
No. This will be hard. The first step is to get bluetooth running at esphome. My dream is a `esp32_ble_tracker` per yeelight device / ceiling lamp. It looks like I've to replace the ESP32 with a dual core version first. As soon I'm able to enable the btle stack at the esp32 we can try to communicate with btle devices. Are you aware of [this](https://github.com/nccchirag/yeelight-ble-rotary-dimmer/issues/1) project?

**Comment by jaddel** [comment]
> h a dual core version first. As soon I'm able to enable the btle stack at the esp32 we can try to communicate with btle devices. Are you

i skipped through it but I'm not familiar with the matter. I looks like Tasmota is already supporting the remote? #yee-rc
https://tasmota.github.io/docs/Bluetooth/#ble-sensors-on-esp32-using-built-in-bluetooth

**Comment by syssi** [comment]
Good catch! I've replaced the ESP32 of one of my lamps by a dual core version already and will give it a try.

**Comment by Ernst79** [comment]
The remote is not encrypted. I recently added it to BLE monitor (it's added and working in 2.0.1-beta, not in master yet). https://github.com/custom-components/ble_monitor/issues/289

Note that in that topic, we discuss the Yeelight remote (which is not encrypted) and the rotating dimmer. the last is not clear, it seems not to follow the MiBeacon protocol, at least it has has a strange format.

**Comment by jaddel** [comment]
awesome, thx. Do you know if this also natively possible using esphome?

**Comment by Ernst79** [comment]
The info was meant for @syssi to implement it in ESPhome. So it’s not yet in ESPhome, but with the info, it should be easy to add for him, I assume.

**Comment by syssi** [comment]
I've prepared a esphome PR: https://github.com/esphome/esphome/pull/1783

**Comment by jaddel** [comment]
Could you give me a hint how i can mange to get your custom integration for the BLE remote to work until your commit has been added to the esphome master?

**Comment by syssi** [comment]
The `custom_components` folder is used automatically if you keep the directory structure:

```
custom_components/
your-ceiling-lamp.yaml
```

Just add the relevant parts of the `yeerc_ylyk01yl.yaml` to `your-ceiling-lamp.yaml`: 

```
esp32_ble_tracker:

xiaomi_ylyk01yl:
  mac_address: "FF:FF:FF:FF:FF:FF"
  last_button_pressed:
    name: "last button pressed"
  on_button_on:
    then:
      - logger.log: "Button on pressed"
  on_button_off:
    then:
      - logger.log: "Button off pressed"
  on_button_sun:
    then:
      - logger.log: "Button sun pressed"
  on_button_m:
    then:
      - logger.log: "Button m pressed"
  on_button_plus:
    then:
      - logger.log: "Button plus pressed"
  on_button_minus:
    then:
      - logger.log: "Button minus pressed"
```

You've to update the `mac_address` to the MAC address of your remote control. If you have trouble to find the MAC address I can provide some instructions for a linux host.

Please make sure you apply the above configuration to a ceiling lamp equipped with a **ESP32 dual core**.

**Comment by jaddel** [comment]
awesome, it's working!

thank you.

**Comment by syssi** [comment]
@jaddel If you ceiling lamp misses some key presses of the remote control you could play around with these settings:

```
esp32_ble_tracker
  scan_parameters:
    interval: 320ms
    window: 100ms
```

Please be aware: If the `esp32_ble_tracker` blocks the radio of the ESP32 too heavily your WiFi connection fails. You could use a separat ESP32-Nodemcu to play around.
